//
//  DebugBundleSharing.swift
//  Tenney
//
//  Created by Autogenerated on 2025-01-01.
//

import Foundation
#if os(macOS)
import AppKit
#else
import UIKit
#endif

enum DebugBundleSharing {
    static func copyToClipboard(text: String) {
        #if os(macOS)
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
        #else
        UIPasteboard.general.string = text
        #endif
    }

    static func shareFile(url: URL) {
        #if os(macOS)
        guard let view = NSApplication.shared.keyWindow?.contentView else { return }
        let picker = NSSharingServicePicker(items: [url])
        picker.show(relativeTo: view.bounds, of: view, preferredEdge: .minY)
        #else
        guard let root = UIApplication.shared.connectedScenes
            .compactMap({ $0 as? UIWindowScene })
            .flatMap({ $0.windows })
            .first(where: { $0.isKeyWindow })?.rootViewController else { return }

        let activity = UIActivityViewController(activityItems: [url], applicationActivities: nil)
        activity.popoverPresentationController?.sourceView = root.view
        root.present(activity, animated: true)
        #endif
    }
}
