import Foundation

enum ScalaExporter {

    static func sclText(scaleName: String, description: String, degrees: [RatioRef]) -> String {
        let title = scaleName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "Untitled" : scaleName
        let desc = description.trimmingCharacters(in: .whitespacesAndNewlines)

        // Convert each RatioRef to a single rational by applying octave to p/q
        func applyOctave(_ r: RatioRef) -> (p: Int, q: Int) {
            var p = r.p
            var q = r.q
            if r.octave > 0 {
                p = p &* (1 << r.octave)
            } else if r.octave < 0 {
                q = q &* (1 << (-r.octave))
            }
            let (P, Q) = RatioMath.reduced(p, q)
            return (P, Q)
        }

        // Dedup + sort by cents
        var seen = Set<String>()
        var rows: [(p: Int, q: Int, cents: Double)] = []
        rows.reserveCapacity(degrees.count)

        for r in degrees {
            let pq = applyOctave(r)
            let key = "\(pq.p)/\(pq.q)"
            if seen.insert(key).inserted {
                let cents = 1200.0 * Darwin.log2(Double(pq.p) / Double(pq.q))
                rows.append((pq.p, pq.q, cents))
            }
        }

        if rows.isEmpty {
            rows = [(1, 1, 0.0)]
        }

        rows.sort { $0.cents < $1.cents }

        var out: [String] = []
        out.append("! \(title).scl")
        out.append("!")
        out.append(desc.isEmpty ? "Generated by Tenney" : desc)
        out.append(String(rows.count))
        out.append("!")

        for r in rows {
            out.append("\(r.p)/\(r.q)")
        }

        return out.joined(separator: "\n")
    }

    static func kbmText(referenceHz: Double, scaleSize: Int) -> String {
        // Minimal KBM that pins A4 (69) to referenceHz and uses “automatic mapping”.
        // This is good enough for export/share + stops the build from failing.
        let hz = (referenceHz.isFinite && referenceHz > 0) ? referenceHz : 440.0
        let octaveDegree = max(1, scaleSize)

        var out: [String] = []
        out.append("! tenney_export.kbm")
        out.append("!")
        out.append("0")          // map size (0 = auto)
        out.append("0")          // first MIDI key to retune
        out.append("127")        // last MIDI key to retune
        out.append("60")         // middle key (where scale degree 0 is placed)
        out.append("69")         // reference key
        out.append(String(hz))   // reference frequency
        out.append("0")          // scale degree for reference key
        out.append(String(octaveDegree)) // formal octave size in scale degrees
        out.append("0")          // (reserved / may be ignored by readers; kept for compatibility)
        return out.joined(separator: "\n")
    }
}
