//
//  SentryService.swift
//  Tenney
//
//  Created by Autogenerated on 2025-01-01.
//

import Foundation
import Sentry

@MainActor
final class SentryService {
    static let shared = SentryService()

    private var enabled = false

    private init() { }

    func setEnabled(_ on: Bool) {
        guard on else {
            enabled = false
            SentrySDK.flush(timeout: 2.0)
            SentrySDK.close()
            return
        }

        guard let dsn = Bundle.main.object(forInfoDictionaryKey: "SentryDSN") as? String else {
            return
        }

        let trimmed = dsn.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        // If Info.plist substitution didn’t occur, you’ll get a literal "$(SENTRY_DSN)".
        // Don’t start Sentry in that case.
        guard !trimmed.contains("$(") else { return }

        // Basic sanity so we don’t “start” with garbage in production.
        guard trimmed.hasPrefix("http"), trimmed.contains("@") else { return }


        guard !enabled else { return }

        SentrySDK.start { options in
            options.dsn = trimmed
            options.sendDefaultPii = false
            options.tracesSampleRate = 0

            #if DEBUG
            options.environment = "debug"
            #else
            options.environment = "release"
            #endif
        }


        enabled = true
    }

    func breadcrumb(category: String, message: String, level: SentryLevel = .info) {
        guard enabled else { return }
        let crumb = Breadcrumb()
        crumb.category = category
        crumb.message = message
        crumb.level = level
        SentrySDK.addBreadcrumb(crumb)
    }

    func captureNonFatal(_ error: Error, context: [String: Any]? = nil) {
        guard enabled else { return }
        let event = Event()
        event.level = .error
        event.message = SentryMessage(formatted: String(describing: error))
        var extras = context ?? [:]
        let logs = DiagnosticsCenter.shared.recentLogLines(limit: 80).joined(separator: "\n")
        if !logs.isEmpty {
            extras["logs"] = logs
        }
        if !extras.isEmpty {
            event.extra = extras
        }
        SentrySDK.capture(event: event)
    }
}
