//
//  SessionCrashMarker.swift
//  Tenney
//
//  Created by Autogenerated on 2025-01-01.
//

import Foundation

struct CrashInfo: Codable {
    let timestamp: Date
    let reason: String
}

final class SessionCrashMarker {
    static let shared = SessionCrashMarker()

    private struct MarkerState: Codable {
        var alive: Bool
        var timestamp: Date
    }

    private let markerURL: URL = {
        let fm = FileManager.default
        let dir = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first?
            .appendingPathComponent("CrashMarker", isDirectory: true) ?? fm.temporaryDirectory
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("session.marker.json")
    }()

    private let queue = DispatchQueue(label: "com.tenney.crashmarker", qos: .utility)

    func onLaunch() -> CrashInfo? {
        var previousCrash: CrashInfo?

        queue.sync {
            let previous = loadMarker()
            if let state = previous, state.alive {
                let info = CrashInfo(timestamp: state.timestamp, reason: "marker")
                previousCrash = info
                UserDefaults.standard.set(state.timestamp.timeIntervalSince1970, forKey: SettingsKeys.lastSessionCrashTimestamp)
                UserDefaults.standard.set(0, forKey: SettingsKeys.lastCrashBannerDismissedAt)
            }

            saveMarker(MarkerState(alive: true, timestamp: Date()))
        }

        return previousCrash
    }

    func markCleanTermination() {
        queue.async { [weak self] in
            guard let self else { return }
            self.saveMarker(MarkerState(alive: false, timestamp: Date()))
        }
    }

    func clearCrashBannerDismissalOnNewCrash() {
        UserDefaults.standard.set(0, forKey: SettingsKeys.lastCrashBannerDismissedAt)
    }

    private func loadMarker() -> MarkerState? {
        guard let data = try? Data(contentsOf: markerURL) else { return nil }
        return try? JSONDecoder().decode(MarkerState.self, from: data)
    }

    private func saveMarker(_ state: MarkerState) {
        guard let data = try? JSONEncoder().encode(state) else { return }
        try? data.write(to: markerURL, options: [.atomic])
    }
}
