name: "Feature Request"
description: "Suggest an improvement to Tenney (performer-first, research-friendly; parity-aware)."
title: "[Feature] "
labels:
  - "type:feature"
  - "status:triage"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Tenney. The best requests are specific, performer-aware, and include context.

        **Parity note:** Tenney Android is under active development (see Android work on branch `android/oss-foundation`).
        If your request should behave the same across platforms, say so.

        **Tip:** If you have an example scale or dataset, attach it (e.g. `.scl`, `.kbm`, Tenney export, CSV).

  - type: textarea
    id: goal
    attributes:
      label: "What are you trying to do?"
      description: "Describe the outcome you want (job-to-be-done)."
      placeholder: "I want to… so that…"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "What’s blocking you today?"
      description: "What’s the current pain, limitation, or workaround?"
      placeholder: "Right now I… which is frustrating because…"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "Proposed change"
      description: "Describe the feature you’d like. Keep it concrete."
      placeholder: "Add/Change…"
    validations:
      required: true

  - type: dropdown
    id: layer
    attributes:
      label: "Component / layer"
      description: "Where should work likely happen?"
      options:
        - "Core (RatioMath / TenneyScale / JSON)"
        - "Formats (Scala / KBM)"
        - "Lattice (selection rules / rendering)"
        - "Tuner"
        - "Builder / Pads"
        - "Library / Organization"
        - "Stage mode"
        - "Export / Interop"
        - "Audio engine"
        - "MIDI"
        - "UI / Navigation"
        - "Build / CI / Tooling"
        - "Docs"
        - "Other / Not sure"
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: "Platform(s)"
      description: "Select all that apply."
      options:
        - label: "Android (Compose)"
        - label: "iOS (iPhone)"
        - label: "iPadOS"
        - label: "macOS"
        - label: "Shared (fixtures/spec/interop)"
    validations:
      required: true

  - type: dropdown
    id: parity
    attributes:
      label: "Parity expectation"
      description: "Should this match behavior across platforms?"
      options:
        - "Android-only is fine"
        - "Must match iOS/iPadOS/macOS behavior (parity)"
        - "Not sure"
    validations:
      required: true

  - type: input
    id: tested_build
    attributes:
      label: "Build / branch tested (optional)"
      description: "If you tested Android, include branch + commit (e.g., android/oss-foundation @ <sha>)."
      placeholder: "android/oss-foundation @ …"
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: "Primary impact"
      description: "What does this improve most?"
      options:
        - "Performance (stage / rehearsal)"
        - "Research / analysis"
        - "Collaboration / sharing"
        - "Accessibility / clarity"
        - "Speed / efficiency"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance criteria"
      description: "What would make this feature 'done'? (bullet points are great)"
      placeholder: |
        - When I …
        - Tenney should …
        - Edge case: …
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Urgency"
      options:
        - "Nice to have"
        - "Important"
        - "Blocking (can’t proceed without it)"
    validations:
      required: true

  - type: input
    id: os_versions
    attributes:
      label: "OS version(s) (optional)"
      description: "Examples: Android 15, iOS 18.2, macOS 15.1"
      placeholder: "Android … / iOS … / macOS …"
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: "Examples / references (optional)"
      description: "Links, screenshots, or other tools you’re referencing."
      placeholder: "Links or images…"
    validations:
      required: false

  - type: textarea
    id: data
    attributes:
      label: "Example scale or data (optional)"
      description: "If relevant, attach files or paste a minimal example."
      placeholder: "Attach .scl / .kbm / Tenney export / CSV, or paste a small excerpt…"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Anything else?"
      description: "Extra context, edge cases, constraints, or notes."
      placeholder: "Notes…"
    validations:
      required: false
